# This file was generated by GoReleaser. DO NOT EDIT.
class TtnLwStack < Formula
  desc "The Things Stack for LoRaWAN"
  homepage "https://www.thethingsnetwork.org"
  version "3.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rvolosatovs/lorawan-stack/releases/download/v3.1.1/lorawan-stack_3.1.1_darwin_amd64.tar.gz"
    sha256 "4ac6a73e33850fc7da6098bfb677b117fabe16b57f8de6c9a53b8c790432543e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rvolosatovs/lorawan-stack/releases/download/v3.1.1/lorawan-stack_3.1.1_linux_amd64.tar.gz"
      sha256 "b74c3bac33db40bbb73f5362f30bcb6b181216e4107f16e2ee2343ab5b29cda7"
    end
  end
  
  conflicts_with "ttn-lw-cli"

  def install
    bin.install "ttn-lw-cli"
    libexec.install %w[ttn-lw-stack public doc]
    env = {
        :TTN_LW_HTTP_STATIC_SEARCH_PATH => libexec/"public"
    }
    (bin/"ttn-lw-stack").write_env_script libexec/"ttn-lw-stack", env
  end
end
