# This file was generated by GoReleaser. DO NOT EDIT.
class TtnLwCli < Formula
  desc "CLI of The Things Stack for LoRaWAN"
  homepage "https://www.thethingsnetwork.org"
  version "3.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rvolosatovs/lorawan-stack/releases/download/v3.2.1/lorawan-stack-cli_3.2.1_darwin_amd64.tar.gz"
    sha256 "b7a86a3ed0dfc7f96c98779f6daa6f77515d4dc9f5dc2026ddd9f8e906ebf5c9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rvolosatovs/lorawan-stack/releases/download/v3.2.1/lorawan-stack-cli_3.2.1_linux_amd64.tar.gz"
      sha256 "25c7f449fb97ad39ef787ea4c4a055cb214aed15fcb500fd1114f6c0cfb25635"
    end
  end
  
  conflicts_with "ttn-lw-stack"

  def install
    bin.install "ttn-lw-cli"
    libexec.install doc
  end
end
