# This file was generated by GoReleaser. DO NOT EDIT.
class TtnLwCli < Formula
  desc "CLI of The Things Stack for LoRaWAN"
  homepage "https://www.thethingsnetwork.org"
  version "3.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rvolosatovs/lorawan-stack/releases/download/v3.2.1/lorawan-stack-cli_3.2.1_darwin_amd64.tar.gz"
    sha256 "234ded299cc68a6b9e114646195de1a7bdb68792cb7de0c474d79b0e8c70e2f9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rvolosatovs/lorawan-stack/releases/download/v3.2.1/lorawan-stack-cli_3.2.1_linux_amd64.tar.gz"
      sha256 "cbfdc51284f85bfb32bf146bd7d5658502ccc202e0711190a4829767557d8f52"
    end
  end
  
  conflicts_with "ttn-lw-stack"

  def install
    bin.install "ttn-lw-cli"
    libexec.install doc
  end
end
