# This file was generated by GoReleaser. DO NOT EDIT.
class TtnLwStack < Formula
  desc "The Things Stack for LoRaWAN"
  homepage "https://www.thethingsnetwork.org"
  version "3.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rvolosatovs/lorawan-stack/releases/download/v3.2.1/lorawan-stack_3.2.1_darwin_amd64.tar.gz"
    sha256 "ded72d53acc4a13c364dc8cbcc405408113205e4a223f3d05245a66911e3f535"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rvolosatovs/lorawan-stack/releases/download/v3.2.1/lorawan-stack_3.2.1_linux_amd64.tar.gz"
      sha256 "954a147ee408720059c9647bfb21e096beeb0cf055f94fb6625ae0fb9568e251"
    end
  end
  
  conflicts_with "ttn-lw-cli"

  def install
    bin.install "ttn-lw-cli"
    libexec.install %w[ttn-lw-stack public doc]
    env = {
        :TTN_LW_HTTP_STATIC_SEARCH_PATH => libexec/"public"
    }
    (bin/"ttn-lw-stack").write_env_script libexec/"ttn-lw-stack", env
  end
end
